[package]
name             = "withdraw_circuit"
type             = "bin"                   # stays "bin" for an executable circuit
compiler_version = "1.0.0"                 # whatever you’re on
# add or change this line:
entry            = "src/withdraw.nr"
[dependencies]